config/routes.rb
Tennisapp::Application.routes.draw do

  resources :courts

end

app/models/court.rb
class Court
  include Mongoid::Document
  field :number, type: Integer
  field :booked, type: Boolean

  validates :number, numericality: true, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController

	def index
		@courts = Court.all
	end

	def new
		@court = Court.new
	end

	def create
		@court = Court.new(court_params)
		if @court.save
			redirect_to action: 'index'
			flash[:notice] = 'You successfully saved new court data!'
		else
			render action: 'new'
		end
	end

	def edit
		@court = Court.find(params[:id])
		render action: 'new'
	end

	def update
		@court = Court.find(params[:id])
		if @court.update(court_params)
			redirect_to action: 'index'
			flash[:notice] = 'You have edited the court information!'
		else
			render action: 'edit'
		end
	end

	def destroy
		@court = Court.find(params[:id])
		@court.destroy
		redirect_to courts_url
	end

private

	def court_params
		params.require(:court).permit(:number, :booked)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/edit.html.erb
<h1>Edit court</h1>

<%= render 'form' %>

<%= link_to 'Back', courts_path %>

app/views/courts/index.html.erb
<h1>Welcome to the Tennis Club!</h1>
<br />
<p id="notice"><%= notice %></p>
<p>Tennis courts available for booking:</p>
<br />
<br />
<table>
	<thead>
		<tr>
			<th>Court</th>
			<th>Booking Status</th>
			<th class="link_column"></th>
			<th class="link_column"></th>
		</tr>
	</thead>
	<tbody>
		<% @courts.each do |court| %>
		<tr>
			<td>Court <%= court.number %></td>
			<td><%= court.booked ? "booked" : "open"%></td>
			<td class="link_column"><%= link_to 'Edit', edit_court_path(court) %></td>
			<td class="link_column"><%= link_to 'Remove', court, method: :delete, data: {confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<br />
<%= link_to 'Create new court', new_court_path %>

app/views/courts/new.html.erb
<h1>Add a tennis court</h1>
<%= form_for @court do |f| %>
<p>
	<%= f.label :"Court Number: " %>
	<%= f.text_field :number %>
</p>
<p>
	<%= f.label :"Booked: " %>
	<%= f.select :booked, [['booked', true], ['open', false]] %>
</p>

<p><%= f.submit %></p>
<% end %>
<br />
<%= link_to 'Back', courts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tennisapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>